[package]
name = "physical_memory"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
path = "src/physical_memory.rs"

[dependencies]
config = { workspace = true }
rtc = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
