[package]
name = "gui"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[[bin]]
name = "amiga-studio"
path = "src/main.rs"

[dependencies]
eframe = { version = "0.31", default-features = true }
egui = { version = "0.31", default-features = true }
config = { path = "../config" }
rtc = { path = "../rtc" }
memory_bus = { path = "../memory_bus" }
m68000 = { path = "../m68000" }
debugger = { path = "../debugger" }
serde = { workspace = true }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
rfd = "0.15"

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"
console_error_panic_hook = "0.1"
web-sys = { version = "0.3", features = ["Document", "Element", "HtmlCanvasElement", "Window"] }
