[package]
name = "memory_bus"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[lib]
path = "src/memory_bus.rs"

[dependencies]
physical_memory = { workspace = true }
agnus = { workspace = true }
denise = { workspace = true }
paula = { workspace = true }
cia = { workspace = true }
rtc = { workspace = true }
floppy = { workspace = true }

[dev-dependencies]
config = { workspace = true }
