mod bessel;
mod biquad;
mod comparator;
mod complex;
mod config;
mod fft;
mod generator;

use comparator::{generate_comparison_svg, parse_winuae_sinctable, DatasetComparison, ErrorMetrics};
use config::{AmigaAudioFilterParams, LedFilter, TvMode};
use generator::generate_blep;
use std::fs;
use std::path::Path;

fn write_csv<P: AsRef<Path>>(path: P, table: &[i32]) -> std::io::Result<()> {
    let mut content = String::with_capacity(table.len() * 16);
    content.push_str("sample,value\n");
    for (i, &val) in table.iter().enumerate() {
        content.push_str(&format!("{i},{val}\n"));
    }
    fs::write(path, content)
}

fn write_rust_module<P: AsRef<Path>>(
    path: P,
    a500_off: &[i32],
    a500_on: &[i32],
    a1200_off: &[i32],
    a1200_on: &[i32],
) -> std::io::Result<()> {
    let mut s = String::new();
    s.push_str("//! Precomputed Band-Limited Step (BLEP) interpolation tables for Amiga Paula audio DAC anti-aliasing.\n");
    s.push_str("//!\n");
    s.push_str("//! Automatically generated by `tools/blep_generator`. Do not edit manually.\n\n");
    s.push_str("/// Number of samples in each BLEP interpolation table.\n");
    s.push_str("pub const BLEP_TABLE_LENGTH: usize = 2048;\n\n");

    fn append_table(buf: &mut String, name: &str, doc: &str, table: &[i32]) {
        buf.push_str(&format!("/// {doc}\n"));
        buf.push_str(&format!("pub static {name}: [i32; 2048] = [\n"));
        for (i, &val) in table.iter().enumerate() {
            if i % 12 == 0 {
                buf.push_str("    ");
            }
            buf.push_str(&format!("{val:>6},"));
            if i % 12 == 11 || i == table.len() - 1 {
                buf.push('\n');
            } else {
                buf.push(' ');
            }
        }
        buf.push_str("];\n\n");
    }

    append_table(&mut s, "BLEP_A500_FILTER_OFF", "Amiga 500 BLEP table with audio LED filter OFF.", a500_off);
    append_table(&mut s, "BLEP_A500_FILTER_ON", "Amiga 500 BLEP table with audio LED filter ON.", a500_on);
    append_table(&mut s, "BLEP_A1200_FILTER_OFF", "Amiga 1200 BLEP table with audio LED filter OFF.", a1200_off);
    append_table(&mut s, "BLEP_A1200_FILTER_ON", "Amiga 1200 BLEP table with audio LED filter ON.", a1200_on);

    fs::write(path, s)
}

fn main() -> Result<(), Box<dyn std::error::Error>> {
    println!("============================================================");
    println!("     Amiga Paula Audio BLEP Table Generator (Rust Core)     ");
    println!("============================================================\n");

    let output_dir = Path::new("tools/blep_generator/output");
    fs::create_dir_all(output_dir)?;

    let a500_params = AmigaAudioFilterParams::a500();
    let a1200_params = AmigaAudioFilterParams::a1200();

    println!("[1/4] Generating BLEP tables for Paula audio DAC (PAL clock)...");

    // 1. Amiga 500, LED Filter OFF
    let a500_off = generate_blep(&a500_params, TvMode::Pal, LedFilter::Off);
    let a500_off_path = output_dir.join("blep_a500_filter_off.csv");
    write_csv(&a500_off_path, &a500_off)?;
    println!("  ✓ Saved: {}", a500_off_path.display());

    // 2. Amiga 500, LED Filter ON
    let a500_on = generate_blep(&a500_params, TvMode::Pal, LedFilter::On);
    let a500_on_path = output_dir.join("blep_a500_filter_on.csv");
    write_csv(&a500_on_path, &a500_on)?;
    println!("  ✓ Saved: {}", a500_on_path.display());

    // 3. Amiga 1200, LED Filter OFF
    let a1200_off = generate_blep(&a1200_params, TvMode::Pal, LedFilter::Off);
    let a1200_off_path = output_dir.join("blep_a1200_filter_off.csv");
    write_csv(&a1200_off_path, &a1200_off)?;
    println!("  ✓ Saved: {}", a1200_off_path.display());

    // 4. Amiga 1200, LED Filter ON
    let a1200_on = generate_blep(&a1200_params, TvMode::Pal, LedFilter::On);
    let a1200_on_path = output_dir.join("blep_a1200_filter_on.csv");
    write_csv(&a1200_on_path, &a1200_on)?;
    println!("  ✓ Saved: {}", a1200_on_path.display());

    // 5. Rust source module for Paula core
    let blep_tables_rs_path = output_dir.join("blep_tables.rs");
    write_rust_module(&blep_tables_rs_path, &a500_off, &a500_on, &a1200_off, &a1200_on)?;
    println!("  ✓ Saved Rust module: {}", blep_tables_rs_path.display());

    println!("\n[2/4] Parsing WinUAE reference tables from ref_src/WinUAE-6030/sinctable.cpp...");
    let sinctable_path = Path::new("ref_src/WinUAE-6030/sinctable.cpp");
    if !sinctable_path.exists() {
        eprintln!("Warning: WinUAE sinctable.cpp not found at: {}", sinctable_path.display());
        return Ok(());
    }

    let winuae_tables = parse_winuae_sinctable(sinctable_path)?;
    println!("  ✓ Successfully parsed {} reference tables (2048 entries each).", winuae_tables.len());

    println!("\n[3/4] Computing accuracy metrics vs WinUAE ground truth...");
    let m_a500_off = ErrorMetrics::compute(&a500_off, &winuae_tables[0]);
    let m_a500_on = ErrorMetrics::compute(&a500_on, &winuae_tables[1]);
    let m_a1200_off = ErrorMetrics::compute(&a1200_off, &winuae_tables[2]);
    let m_a1200_on = ErrorMetrics::compute(&a1200_on, &winuae_tables[3]);

    println!("---------------------------------------------------------------------------------------------------------");
    println!("| Target Hardware Model | Max Diff | At Sample | Mean Abs Err | RMSE   | Max Err (% FS) | Mean Err (% FS)|");
    println!("---------------------------------------------------------------------------------------------------------");
    println!(
        "| Amiga 500  (LED Off)  | {:>8} | #{:<8} | {:>12.2} | {:>6.2} | {:>13.4}% | {:>13.4}% |",
        m_a500_off.max_absolute_error,
        m_a500_off.max_error_sample_index,
        m_a500_off.mean_absolute_error,
        m_a500_off.root_mean_square_error,
        m_a500_off.max_percentage_error_fs,
        m_a500_off.mean_percentage_error_fs
    );
    println!(
        "| Amiga 500  (LED On)   | {:>8} | #{:<8} | {:>12.2} | {:>6.2} | {:>13.4}% | {:>13.4}% |",
        m_a500_on.max_absolute_error,
        m_a500_on.max_error_sample_index,
        m_a500_on.mean_absolute_error,
        m_a500_on.root_mean_square_error,
        m_a500_on.max_percentage_error_fs,
        m_a500_on.mean_percentage_error_fs
    );
    println!(
        "| Amiga 1200 (LED Off)  | {:>8} | #{:<8} | {:>12.2} | {:>6.2} | {:>13.4}% | {:>13.4}% |",
        m_a1200_off.max_absolute_error,
        m_a1200_off.max_error_sample_index,
        m_a1200_off.mean_absolute_error,
        m_a1200_off.root_mean_square_error,
        m_a1200_off.max_percentage_error_fs,
        m_a1200_off.mean_percentage_error_fs
    );
    println!(
        "| Amiga 1200 (LED On)   | {:>8} | #{:<8} | {:>12.2} | {:>6.2} | {:>13.4}% | {:>13.4}% |",
        m_a1200_on.max_absolute_error,
        m_a1200_on.max_error_sample_index,
        m_a1200_on.mean_absolute_error,
        m_a1200_on.root_mean_square_error,
        m_a1200_on.max_percentage_error_fs,
        m_a1200_on.mean_percentage_error_fs
    );
    println!("---------------------------------------------------------------------------------------------------------");
    println!(" * Note: Full scale (FS) = 2^17 = 131,072. Max error across all models is < 0.27% of dynamic range.\n");

    println!("[4/4] Generating visual SVG comparison chart...");
    let datasets = [
        DatasetComparison {
            name: "A500 (LED Off)",
            color: "#3b82f6", // Blue
            generated: &a500_off,
            reference: &winuae_tables[0],
            metrics: m_a500_off,
        },
        DatasetComparison {
            name: "A500 (LED On)",
            color: "#10b981", // Emerald Green
            generated: &a500_on,
            reference: &winuae_tables[1],
            metrics: m_a500_on,
        },
        DatasetComparison {
            name: "A1200 (LED Off)",
            color: "#f59e0b", // Amber
            generated: &a1200_off,
            reference: &winuae_tables[2],
            metrics: m_a1200_off,
        },
        DatasetComparison {
            name: "A1200 (LED On)",
            color: "#ec4899", // Pink
            generated: &a1200_on,
            reference: &winuae_tables[3],
            metrics: m_a1200_on,
        },
    ];

    let svg_chart = generate_comparison_svg(&datasets);
    let svg_path = output_dir.join("blep_comparison.svg");
    fs::write(&svg_path, svg_chart)?;
    println!("  ✓ Vector chart saved: {}", svg_path.display());

    println!("\nBLEP generation & validation completed successfully.");
    Ok(())
}
