[package]
name = "test_runner"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
path = "src/test_runner.rs"

[dependencies]
cpu = { workspace = true }
physical_memory = { workspace = true }
disassembler = { workspace = true }
debugger = { workspace = true }
serde = { workspace = true, features = ["derive", "std"] }
serde_json = { workspace = true, features = ["std"] }
flate2 = { workspace = true }
machine_loop = { workspace = true }
config = { workspace = true }

[[bench]]
name = "bench_instructions"
harness = false

[lints]
workspace = true
