[package]
name = "agnus"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
path = "src/agnus.rs"

[dependencies]
config = { workspace = true }
blitter = { workspace = true }
copper = { workspace = true }
dma = { workspace = true }
serde = { workspace = true, features = ["derive"] }

[lints]
workspace = true
