[package]
name = "machine_loop"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
path = "src/machine_loop.rs"

[dependencies]
agnus = { workspace = true }
cia = { workspace = true }
config = { workspace = true }
denise = { workspace = true }
floppy = { workspace = true }
game_ports = { workspace = true }
joystick = { workspace = true }
keyboard = { workspace = true }
cpu = { workspace = true }
physical_memory = { workspace = true }
memory_bus = { workspace = true }
mouse = { workspace = true }
paula = { workspace = true }
rtc = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
flate2 = { workspace = true }
