[package]
name = "machine_loop"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
agnus = { workspace = true }
audio = { workspace = true }
blitter = { workspace = true }
cia = { workspace = true }
config = { workspace = true }
copper = { workspace = true }
denise = { workspace = true }
dma = { workspace = true }
floppy = { workspace = true }
frame_builder = { workspace = true }
game_ports = { workspace = true }
joystick = { workspace = true }
keyboard = { workspace = true }
m68000 = { workspace = true }
physical_memory = { workspace = true }
memory_bus = { workspace = true }
mouse = { workspace = true }
parallel_port = { workspace = true }
paula = { workspace = true }
rtc = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serial_port = { workspace = true }
sprites = { workspace = true }
