[package]
name = "debugger"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
path = "src/debugger.rs"

[dependencies]
config = { workspace = true }
disassembler = { workspace = true }
cpu = { workspace = true }
machine_loop = { workspace = true }
physical_memory = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
