[package]
name = "game_ports"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
path = "src/game_ports.rs"

[dependencies]
serde = { workspace = true, features = ["derive"] }
config = { workspace = true }
mouse = { workspace = true }
joystick = { workspace = true }

[dev-dependencies]
serde_json = { workspace = true }

[lints]
workspace = true
